#ifndef GL_CONST_H
#define GL_CONST_H

#define CNS_GRID "grid"
#define CNS_ROOT "root"
#define CNS_TITLE "title"
#define CNS_WIDTH "width"
#define CNS_HEIGHT "height"
#define CNS_CELLSIZE "cellsize"
#define CNS_STARTX "startx"
#define CNS_STARTY "starty"
#define CNS_FINISHX "finishx"
#define CNS_FINISHY "finishy"
#define CNS_MAP "map"
#define CNS_ROW "row"
#define CNS_POINT "point"
#define CNS_X "x"
#define CNS_Y "y"
#define CNS_G "g"
#define CNS_F "F"
#define CNS_NUMBER "number"
#define CNS_ALGORITHM "algorithm"
#define CNS_SEARCHTYPE "searchtype"
#define CNS_METRICTYPE  "metrictype"
#define CNS_HWEIGHT "hweight"
#define CNS_BREAK "breakingties"
#define CNS_LINE "linecost"
#define CNS_DIAGONAL "diagonalcost"
#define CNS_ALLOW "allowdiagonal"
#define CNS_ALLOWS "allowsqueeze"
#define CNS_CUTCORNERS "cutcorners"
#define CNS_OPTIONS "options"
#define CNS_LOGLEVEL "loglevel"
#define CNS_LOGPATH "logpath"
#define CNS_LOGFILENAME "logfilename"

#define CNS_ASTAR "astar"
#define CNS_THETA "theta"
#define CNS_JPS "jp_search"

#define CNS_GMAX "g-max"
#define CNS_GMIN "g-min"

#define CNS_EUCLID "euclid"
#define CNS_MANHATTAN "manhattan"
#define CNS_OCTILE "diagonal"
#define CNS_CHEB "chebyshev"

#define CNS_LOG "log"
#define CNS_MAPFILENAME "mapfilename"
#define CNS_NUMBEROFSTEPS "numberofsteps"
#define CNS_NODES "nodescreated"
#define CNS_LENGTH "length"
#define CNS_PATH "path"
#define CNS_TIME "time"

#define CNS_LPLEVEL "lplevel"
#define CNS_HPLEVEL "hplevel"
#define CNS_NODE "node"
#define CNS_SECTION "section"
#define CNS_START_X "start.x"
#define CNS_START_Y "start.y"
#define CNS_FINISH_X "finish.x"
#define CNS_FINISH_Y "finish.y"

#define CNS_STEP "step"
#define CNS_LOWLEV "lowlevel"
#define CNS_OPEN "open"
#define CNS_CLOSE "close"
#define CNS_PARENT_X "parent_x"
#define CNS_PARENT_Y "parent_y"

#define CN_CELL_IS_BLOCKED 1
#define CN_CELL_IS_NOT_BLOCKED 0

#define CNS_MAPSTAT "mapstat"
#define CNS_SUMMARY "summary"
#define CNS_OBSTACLECOUNT "obstaclecount"
#define CNS_DENSITY "density"
#define CNS_TOTALAREA "totalarea"
#define CNS_TOTALPERIMETER "totalperimeter"
#define CNS_AVERAGEAREA "averagearea"
#define CNS_AVERAGEPERIMETR "averageperimeter"
#define CNS_AREADISPERSION "areadispersion"
#define CNS_PERIMETERDISPERSION "perimeterdispersion"
#define CNS_OBSTACLES "obstacles"
#define CNS_OBSTACLE "obstacle"
#define CNS_PERIMETER "perimeter"
#define CNS_AREA "area"

#endif // GL_CONST_H
